services:
  catalogDb:
    image: postgres:14-alpine
    
  basketDb:
    image: postgres:14-alpine
  
  distributedCache:
    image: redis:7.4.1-alpine
    
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:

